# Generated by Django 6.0.2 on 2026-02-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='consultation_fee',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='college',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.CharField(default='Not Added', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
